# ArXiv 论文采集工具 - 默认配置
# @package _global_

# 搜索参数配置
search:
  field:
    "all" # 搜索领域，支持以下格式：
    # 单个: "ai", "robotics", "cv", "nlp"
    # 并集: "ai+robotics", "ai|cv", "ai or nlp"
    # 交集: "ai&robotics" (注意：ArXiv API限制，实际为并集)
    # 直接分类: "cs.AI", ["cs.AI", "cs.LG"]
    # 可用领域: all, ai, robotics, cv, nlp, physics, math, stat, eess, q-bio
  days: 30 # 搜索天数
  max_results: 500 # 最大获取结果数
  max_display: 0 # 最大显示数量
  min_score: 0.15 # 最小评分阈值

# 关键词配置
interest_keywords:
  - "*" # 通配符，匹配所有论文

exclude_keywords:
  - "medical"
  - "clinical"
  - "healthcare"
  - "pharmaceutical"
  - "drug"
  - "disease"
  - "pure mathematics"
  - "theoretical physics"

# 必须包含关键词配置（支持模糊匹配）
required_keywords:
  enabled: false # 是否启用必须包含关键词过滤
  fuzzy_match: true # 是否启用模糊匹配
  similarity_threshold: 0.8 # 模糊匹配相似度阈值（0-1）
  keywords: [] # 必须包含的关键词列表，论文必须至少包含其中一个
  # 示例配置：
  # keywords:
  #   - "robot"  # 会匹配 robot, robots, robotics, robotic 等
  #   - "neural network"  # 会匹配 neural networks, neural-network 等
  #   - "deep AND learning"  # AND逻辑：必须同时包含deep和learning

# 智能匹配配置
intelligent_matching:
  enabled: false # 默认关闭智能匹配
  score_weights:
    base: 1.0 # 基础匹配权重
    semantic: 0.3 # 语义增强权重
    author: 0.2 # 作者分析权重
    novelty: 0.4 # 新颖性权重
    citation: 0.3 # 引用潜力权重
  fuzzy_threshold: 0.8 # 模糊匹配阈值
  time_decay_days: 30 # 时间衰减天数

# PDF下载配置
download:
  enabled: false # 默认不下载PDF
  max_downloads: 10 # 最大下载数量
  download_dir: "downloads" # 下载目录
  create_metadata: true # 创建元数据文件
  create_index: true # 创建索引文件
  force_download: false # 强制重新下载

# 显示配置
display:
  show_ranking: true # 显示排序
  show_scores: true # 显示评分
  show_breakdown: false # 显示评分分解（仅智能匹配时有效）
  stats: true # 显示统计信息

# 输出配置
output:
  save: false # 保存报告
  save_keywords: false # 保存关键词信息
  include_scores: true # 包含评分信息
  format: "markdown" # 输出格式: markdown, txt

# 飞书同步配置
feishu:
  enabled: true # 默认关闭飞书同步
  auto_sync: true # 自动判断同步时机
  field_id: "" # 领域ID，为空时使用user_profile.research_area
  field_name: "" # 领域显示名称，为空时使用user_profile.name去掉"研究员"
  sync_threshold: 0.3 # 最低评分阈值
  batch_size: 50 # 批次处理大小
  preserve_low_scores: true # 保留低分论文记录
  update_existing: true # 更新已有记录
  sync_interval_hours: 6 # 自动同步间隔(小时)

  # 飞书API配置（使用环境变量）
  api:
    app_id: ${oc.env:FEISHU_APP_ID,""} # 从环境变量FEISHU_APP_ID读取
    app_secret: ${oc.env:FEISHU_APP_SECRET,""} # 从环境变量FEISHU_APP_SECRET读取
    # 访问令牌配置（二选一）
    user_access_token: ${oc.env:FEISHU_USER_ACCESS_TOKEN,""} # 用户访问令牌
    tenant_access_token: ${oc.env:FEISHU_TENANT_ACCESS_TOKEN,""} # 应用访问令牌
    base_url: "https://open.feishu.cn/open-apis" # API基础URL
    timeout: 30 # 请求超时时间(秒)
    max_retries: 3 # 最大重试次数
    retry_delay: 1.0 # 重试间隔(秒)

  # Wiki文档配置
  wiki:
    space_token: ${oc.env:FEISHU_WIKI_SPACE_TOKEN,""} # Wiki空间token，如: BR1CwZrcaiFyYfkUEMEcZ6aunMj
    papers_node_token: ${oc.env:FEISHU_PAPERS_NODE_TOKEN,""} # 论文节点token
    relations_node_token: ${oc.env:FEISHU_RELATIONS_NODE_TOKEN,""} # 关系节点token

  # 视图管理配置
  # TODO:排序条件似乎无效
  views:
    enabled: true # 是否启用视图管理
    auto_cleanup: true # 是否自动清理多余视图
    create_views: # 需要创建的视图列表
      - name: "评分排序视图"
        type: "sort"
        description: "按相关性评分降序排列"
        sorts:
          - field: "相关性评分"
            direction: "desc"

      - name: "时间排序视图"
        type: "sort"
        description: "按发布时间降序排列"
        sorts:
          - field: "发布日期"
            direction: "desc"

  # 多维表格配置
  bitable:
    app_token: ${oc.env:FEISHU_BITABLE_APP_TOKEN,""} # 多维表格的app_token
    papers_table_id: ${oc.env:FEISHU_PAPERS_TABLE_ID,""} # 论文主表ID
    relations_table_id: ${oc.env:FEISHU_RELATIONS_TABLE_ID,""} # 领域关系表ID

  # 群聊通知配置
  chat_notification:
    enabled: true # 是否启用群聊通知
    notify_on_update: true # 有论文更新时发送通知
    notify_on_new_papers: true # 有新论文时发送通知
    min_papers_threshold: 1 # 最少论文数量才发送通知
    max_recommended_papers: 1 # 每个领域推荐的论文数量
    message_template: "default" # 消息模板类型
    send_delay_seconds: 0.5 # 发送消息间隔(秒)，避免发送过快

# 用户配置信息（可选）
user_profile:
  name: "通用研究员"
  description: "通用配置，适用于各种研究领域"
  research_area: "general"

description: "ArXiv 论文采集工具默认配置"
