#!/bin/bash
# ArXiv论文定时采集系统 - 快速使用指南

echo "🚀 ArXiv论文定时采集系统"
echo "================================"
echo ""
echo "✅ 已完成设置："
echo "   - 每天上午10:00（中国时间）自动执行论文采集"
echo "   - 命令: python3 arxiv_hydra.py --config-name=all"
echo "   - 日志保存在 logs/daily_sync_YYYYMMDD.log"
echo ""
echo "📋 可用命令："
echo "   ./scripts/setup_daily_sync.sh status      # 查看定时任务状态"
echo "   ./scripts/setup_daily_sync.sh test        # 手动测试执行"
echo "   ./scripts/setup_daily_sync.sh logs        # 查看历史日志"
echo "   ./scripts/setup_daily_sync.sh uninstall   # 卸载定时任务"
echo "   ./scripts/daily_arxiv_sync.sh             # 直接运行采集脚本"
echo ""
echo "📅 定时任务已安装到系统crontab："
crontab -l | grep "daily_arxiv_sync.sh"
echo ""
echo "🕒 当前系统时间: $(date)"
echo "🌏 当前时区: $(timedatectl show --property=Timezone --value 2>/dev/null || date +%Z)"
echo ""
echo "📂 重要文件："
echo "   scripts/daily_arxiv_sync.sh       # 主执行脚本"
echo "   scripts/setup_daily_sync.sh       # 管理脚本"
echo "   scripts/crontab_daily_sync        # Crontab配置模板"
echo "   scripts/README_daily_sync.md      # 详细文档"
echo "   logs/daily_sync_*.log             # 执行日志"
echo ""
echo "💡 下次执行时间: 明天上午10:00"
